name: Upload to Discord(Custom)

on: 
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Send file README.md to discord channel
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          FILES: ${{ secrets.PATH_TO_FILES }}
        run: |
          if [[ -z "$FILES" ]]; then
            echo "You need to provide a file or files to send."
            exit 1
          fi
          for f in $FILES; do
            if [[ ! -f "$f" ]]; then
              echo "The variable '$f' is not a file or does not exist. Files must not have a space in the name."
              exit 1
            curl -H 'Content-Type: multipart/form-data' \
            -X POST \
            -F "file=@$f" $DISCORD_WEBHOOK
          done
